seeds = ["standard", "empty"]

fuzzers = ["afl",
			"aflq",
			"afld",
			"fairfuzz",
			"afl-li",
			"afl-cf",
			"aflfast",
			"aflpp"]

targets = ["CGC_AIS-Lite",
			"CGC_basic_emulator",
			"CGC_BitBlaster",
			"CGC_Cereal_Mixup",
			"CGC_CNMP",
			"CGC_Differ",
			"CGC_Diophantine",
			"CGC_Divelogger2",
			"CGC_expression_database",
			"CGC_FileSys",
			"CGC_FSK_MS",
			"CGC_humaninterface",
			"CGC_Image_Compressor",
			"CGC_LazyCalc",
			"CGC_LSIMP",
			"CGC_Matrix_Math",
			"CGC_middleout",
			"CGC_Movie_Rental",
			"CGC_Multi_User_Calendar",
			"CGC_Multipass",
			"CGC_One_Amp",
			"CGC_online_job_application2",
			"CGC_Palindrome",
			"CGC_Palindrome2",
			"CGC_Particle_Simulator",
			"CGC_Personal_Fitness_Manager",
			"CGC_Printer",
			"CGC_REMATCH_3",
			"CGC_Resort_Modeller",
			"CGC_root64_and_parcour",
			"CGC_SAuth",
			"CGC_SFTSCBSISS",
			"CGC_ShoutCTF",
			"CGC_Simple_Stack_Machine",
			"CGC_Space_Attackers",
			"CGC_Square_Rabbit",
			"CGC_stream_vm",
			"CGC_stream_vm2",
			"CGC_Thermal_Controller_v2",
			"CGC_User_Manager",
			"CGC_XStore",
			"CGC_yolodex"]

targets_empty =["CGC_AIS-Lite",
				"CGC_basic_emulator",
				"CGC_BitBlaster",
				"CGC_Cereal_Mixup",
				"CGC_CNMP",
				"CGC_Diophantine",
				"CGC_FileSys",
				"CGC_FSK_MS",
				"CGC_humaninterface",
				"CGC_Image_Compressor",
				"CGC_LazyCalc",
				"CGC_LSIMP",
				"CGC_Matrix_Math",
				"CGC_middleout",
				"CGC_Multi_User_Calendar",
				"CGC_Multipass",
				"CGC_One_Amp",
				"CGC_Palindrome",
				"CGC_Palindrome2",
				"CGC_Particle_Simulator",
				"CGC_Personal_Fitness_Manager",
				"CGC_Printer",
				"CGC_REMATCH_3",
				"CGC_Resort_Modeller",
				"CGC_root64_and_parcour",
				"CGC_SAuth",
				"CGC_SFTSCBSISS",
				"CGC_ShoutCTF",
				"CGC_Simple_Stack_Machine",
				"CGC_Space_Attackers",
				"CGC_Square_Rabbit",
				"CGC_stream_vm2",
				"CGC_Thermal_Controller_v2",
				"CGC_XStore",
				"CGC_yolodex"]

targets_cwe = {"CGC_AIS-Lite":[20, 120, 122, 129, 788],
				"CGC_basic_emulator":[170],
				"CGC_BitBlaster":[476, 824],
				"CGC_Cereal_Mixup":[502, 822],
				"CGC_CNMP":[134],
				"CGC_Differ":[121],
				"CGC_Diophantine":[476, 824],
				"CGC_Divelogger2":[119],
				"CGC_expression_database":[119],
				"CGC_FileSys":[416],
				"CGC_FSK_MS":[120, 122],
				"CGC_humaninterface":[122],
				"CGC_Image_Compressor":[787],
				"CGC_LazyCalc":[121],
				"CGC_LSIMP":[843],
				"CGC_Matrix_Math":[121],
				"CGC_middleout":[121, 788, 787],
				"CGC_Movie_Rental":[134],
				"CGC_Multi_User_Calendar":[121],
				"CGC_Multipass":[822],
				"CGC_One_Amp":[121],
				"CGC_online_job_application2":[120, 122],
				"CGC_Palindrome":[121],
				"CGC_Palindrome2":[121],
				"CGC_Particle_Simulator":[787],
				"CGC_Personal_Fitness_Manager":[121, 131],
				"CGC_Printer":[122],
				"CGC_REMATCH_3":[121],
				"CGC_Resort_Modeller":[468, 822],
				"CGC_root64_and_parcour":[121],
				"CGC_SAuth":[121, 190],
				"CGC_SFTSCBSISS":[120],
				"CGC_ShoutCTF":[121],
				"CGC_Simple_Stack_Machine":[122],
				"CGC_Space_Attackers":[121],
				"CGC_Square_Rabbit":[190],
				"CGC_stream_vm":[127],
				"CGC_stream_vm2":[129, 665, 787],
				"CGC_Thermal_Controller_v2":[121],
				"CGC_User_Manager":[416],
				"CGC_XStore":[121],
				"CGC_yolodex":[787]}